services:
  - name: api-service
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: AI_SERVICE_URL
        value: https://ai-service.onrender.com

  - name: ai-service
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"

  - name: order-service
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"

  - name: websocket-service
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn socket:app --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT"
